version: '3.1'
services:
  codeception:
    image: codeception/codeception
    volumes:
      - .:/project
    depends_on:
      - selenium-hub
      - selenium-node-chrome
    env_file: ./.env
    environment:
      - WEBSITE_FRONTEND_URL=http://google.de
    entrypoint: codecept


  selenium-hub:
    image: selenium/hub
    logging:
        driver: none


  selenium-node-chrome:
    image: selenium/node-chrome
    env_file: ./.env
    links:
      - selenium-hub
    depends_on:
      - selenium-hub
    environment:
      - WEBSITE_FRONTEND_URL=http://google.de
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
    logging:
        driver: none
    volumes:
      # mount to local /dev/shm as it is too small inside the container
      - /dev/shm:/dev/shm
